name: Run health check
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  run-health-check:
    name: Run health check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: ./actions/health-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
